export const brand3MHex = {
    Gloss: [
        { name: 'Red Metallic (G203)', colorCode: '#8C1A1F' },
        { name: 'Dragon Fire Red (G363)', colorCode: '#CA2726' },
        { name: 'Dark Red (G83)', colorCode: '#CD2027' },
        { name: 'Flame Red (G53)', colorCode: '#CD191D' },
        { name: 'Hot Rod Red (G13)', colorCode: '#DA3526' },
        { name: 'Fiery Orange (G364)', colorCode: '#CA5934' },
        { name: 'Liquid Copper (G344)', colorCode: '#ED4726' },
        { name: 'Burnt Orange (G14)', colorCode: '#F47922' },
        { name: 'Deep Orange (G24)', colorCode: '#F47D20' },
        { name: 'Bright Orange (G54)', colorCode: '#F28420' },
        { name: 'Sunflower (G25)', colorCode: '#EDAC1E' },
        { name: 'Bright Yellow (G15)', colorCode: '#FEC70B' },
        { name: 'Lucid Yellow (G55)', colorCode: '#FFF22A' },
        { name: 'Green Envy (G336)', colorCode: '#07663F' },
        { name: 'Kelly Green (G46)', colorCode: '#129246' },
        { name: 'Light Green (G16)', colorCode: '#75BF4F' },
        { name: 'Atomic Teal (G356)', colorCode: '#079892' },
        { name: 'Midnight Blue (GP272)', colorCode: '#070808' },
        { name: 'Boat Blue (G127)', colorCode: '#0D1625' },
        { name: 'Deep Metallic Blue (G217)', colorCode: '#203167' },
        { name: 'Blue Metallic (G227)', colorCode: '#233269' },
        { name: 'Blue Raspberry (G378)', colorCode: '#2A2977' },
        { name: 'Cosmic Blue (G377)', colorCode: '#0C51A1' },
        { name: 'Intense Blue (G47)', colorCode: '#0B54A0' },
        { name: 'Blue Fire (G337)', colorCode: '#036494' },
        { name: 'Sky Blue (G77)', colorCode: '#52C6EA' },
        { name: 'Fierce Fuchsia (G348)', colorCode: '#C31E64' },
        { name: 'Hot Pink (G103)', colorCode: '#E3477D' },
        { name: 'Black Rose (GP99)', colorCode: '#3A1B1D' },
        { name: 'Plum Explosion (GP258)', colorCode: '#422671' },
        { name: 'Ember Black (GP282)', colorCode: '#1F0803' },
        { name: 'White Aluminum (G120)', colorCode: '#A5A4A3' },
        { name: 'Sterling Silver (G251)', colorCode: '#969696' },
        { name: 'Storm Grey (G31)', colorCode: '#A5A3A0' },
        { name: 'White (G10)', colorCode: '#FFFFFF' },
        { name: 'Light Ivory (G79)', colorCode: '#FAE2AE' },
        { name: 'Galaxy Black (GP292)', colorCode: '#12240C' },
        { name: 'Black Metallic (G212)', colorCode: '#080A09' },
        { name: 'Black (G12)', colorCode: '#050504' },
        { name: 'Anthracite (G201)', colorCode: '#454645' },
        { name: 'Charcoal Metallic (G211)', colorCode: '#444344' }
    ],
    Satin: [
        { name: 'Vampire Red (SP273)', colorCode: '#6A090F' },
        { name: 'Smoldering Red (S363)', colorCode: '#961A1E' },
        { name: 'Bitter Yellow (S335)', colorCode: '#C49B2A' },
        { name: 'Apple Green (S196)', colorCode: '#489C44' },
        { name: 'Key West (S57)', colorCode: '#69C8C9' },
        { name: 'Ocean Shimmer (S327)', colorCode: '#00789D' },
        { name: 'Perfect Blue (S347)', colorCode: '#0273AC' },
        { name: 'Thundercloud (S271)', colorCode: '#2B343E' },
        { name: 'Dark Grey (S261)', colorCode: '#3F3E41' },
        { name: 'Black (S12)', colorCode: '#1A1617' },
        { name: 'Battleship Gray (S51)', colorCode: '#758183' },
        { name: 'White Aluminum (S120)', colorCode: '#C4C2C0' },
        { name: 'Frozen Vanilla (SP240)', colorCode: '#E4E8E0' },
        { name: 'White (S10)', colorCode: '#F9FAF9' },
        { name: 'Pearl White (SP10)', colorCode: '#F0E9D5' }
    ],
    Matte: [
        { name: 'Red Metallic (M203)', colorCode: '#851D21' },
        { name: 'Red (M13)', colorCode: '#EE3E34' },
        { name: 'Pine Green Metallic (M206)', colorCode: '#294C33' },
        { name: 'Military Green (M26)', colorCode: '#3E441B' },
        { name: 'Indigo (M27)', colorCode: '#1A2834' },
        { name: 'Slate Blue Metallic (M217)', colorCode: '#152B4A' },
        { name: 'Blue Metallic (M227)', colorCode: '#3A6BB3' },
        { name: 'Black (M12)', colorCode: '#050504' },
        { name: 'Black Metallic (M212)', colorCode: '#212222' },
        { name: 'Deep Black (M22)', colorCode: '#222323' },
        { name: 'Dead Matte Black (DM12)', colorCode: '#38393B' },
        { name: 'Dark Grey (M261)', colorCode: '#3F403F' },
        { name: 'Grey Aluminum (M230)', colorCode: '#858484' },
        { name: 'Silver (M12)', colorCode: '#939598' },
        { name: 'White (M10)', colorCode: '#F9FAFA' },
        { name: 'Charcoal Metallic (M211)', colorCode: '#4C4738' },
        { name: 'Brown Metallic', colorCode: '#664F37' }
    ],
    Chrome: [
        { name: 'Gloss Silver Chrome (GC451)', colorCode: '#C0C0C0' }
    ]
};

export const brandAvery = {
    Gloss: [
        { name: 'Black (SW900-190-O)', colorCode: '#101115' },
        { name: 'Obsidian Black (SW900-191-O)', colorCode: '#000000' },
        { name: 'Dark Grey (SW900-865-O)', colorCode: '#686868' },
        { name: 'Rock Grey (SW900-821-O)', colorCode: '#909090' },
        { name: 'Grey (SW900-832-O)', colorCode: '#E8E7E3' },
        { name: 'Misty Grey (SW900-8221-O)', colorCode: '#EAEAEA' },
        { name: 'Red (SW900-415-O)', colorCode: '#FE0500' },
        { name: 'Soft Red (SW900-427-O)', colorCode: '#FD2627' },
        { name: 'Cardinal Red (SW900-433-O)', colorCode: '#FE0100' },
        { name: 'Carmine Red (SW900-436-O)', colorCode: '#FE0100' },
        { name: 'Burgundy (SW900-475-O)', colorCode: '#AC0006' },
        { name: 'Indigo Blue (SW900-699-O)', colorCode: '#011D4A' },
        { name: 'Dark Blue (SW900-681-O)', colorCode: '#012EAB' },
        { name: 'Blue (SW900-677-O)', colorCode: '#0090FB' },
        { name: 'Intense Blue (SW900-667-O)', colorCode: '#0093FA' },
        { name: 'Light Blue (SW900-632-O)', colorCode: '#04CBFD' },
        { name: 'Aqua Blue (SW900-636-O)', colorCode: '#00B6CC' },
        { name: 'Sea Breeze Blue (SW900-648-O)', colorCode: '#BCF3F8' },
        { name: 'Smoky Blue (SW900-612-O)', colorCode: '#BAD1E3' },
        { name: 'Cloudy Blue (SW900-656-O)', colorCode: '#E5ECF7' },
        { name: 'Light Pistachio (SW900-728-O)', colorCode: '#E6F0D5' },
        { name: 'Emerald Green (SW900-771-O)', colorCode: '#1FB792' },
        { name: 'Dark Green (SW900-792-O)', colorCode: '#005417' },
        { name: 'Grass Green (SW900-758-O)', colorCode: '#6ADF42' },
        { name: 'Tropical Vacation Green (SW900-701-O)', colorCode: '#74C900' },
        { name: 'Lime Green (SW900-731-O)', colorCode: '#ECFA36' },
        { name: 'Orange (SW900-373-O)', colorCode: '#FE6000' },
        { name: 'Dark Yellow (SW900-249-O)', colorCode: '#FFDF00' },
        { name: 'Yellow (SW900-235-O)', colorCode: '#FEF100' },
        { name: 'Ambulance Yellow (SW900-236-O)', colorCode: '#FEFE82' },
        { name: 'Pool Party Pink (SW900-517-O)', colorCode: '#D4013A' },
        { name: 'White (SW900-101-O)', colorCode: '#F6F6F6' }
    ],
    Gloss_Metallic: [
        { name: 'Black (SW900-192-M)', colorCode: '#141213' },
        { name: 'Grey (SW900-807-M)', colorCode: '#515151' },
        { name: 'Eclipse (SW900-199-M)', colorCode: '#564B35' },
        { name: 'Silver (SW900-803-M)', colorCode: '#959595' },
        { name: 'Quick Silver (SW900-816-M)', colorCode: '#BCBEC9' },
        { name: 'Spark (SW900-419-M)', colorCode: '#C11B23' },
        { name: 'Popstar Concert Purple (SW900-521-M)', colorCode: '#690645' },
        { name: 'Mysterious Indigo (SW900-700-M)', colorCode: '#3A237B' },
        { name: 'Magnetic Burst (SW900-679-M)', colorCode: '#151D65' },
        { name: 'Mystery Black (SW900-184-M)', colorCode: '#0D2E4A' },
        { name: 'Dark Blue (SW900-653-M)', colorCode: '#0C153A' },
        { name: 'Radioactive (SW900-762-M)', colorCode: '#016736' },
        { name: 'Gold (SW900-215-M)', colorCode: '#B8953E' },
        { name: 'Sand Sparkle (SW900-255-M)', colorCode: '#936E56' },
        { name: 'Brown (SW900-929-M)', colorCode: '#886E61' }
    ],
    Matte: [
        { name: 'Black (SW900-180-O)', colorCode: '#141414' },
        { name: 'Dark Grey (SW900-856-O)', colorCode: '#76757A' },
        { name: 'Olive Green (SW900-732-O)', colorCode: '#4D5140' },
        { name: 'Khaki Green (SW900-711-O)', colorCode: '#828476' },
        { name: 'Orange (SW900-321-O)', colorCode: '#FB7100' },
        { name: 'White (SW900-102-O)', colorCode: '#FAF9F7' }
    ],
    Matte_Metallic: [
        { name: 'Gunmetal (SW900-840-M)', colorCode: '#61605C' },
        { name: 'Charcoal (SW900-845-M)', colorCode: '#504F4D' },
        { name: 'Anthracite (SW900-858-M)', colorCode: '#676E71' },
        { name: 'Silver (SW900-857-M)', colorCode: '#C9C9C9' },
        { name: 'Garnet Red (SW900-472-M)', colorCode: '#702320' },
        { name: 'Cherry Matte Metallic (SW900-444-M)', colorCode: '#74001A' },
        { name: 'Purple (SW900-565-M)', colorCode: '#46406E' },
        { name: 'Night Blue (SW900-623-M)', colorCode: '#18233D' },
        { name: 'Brilliant Blue (SW900-671-M)', colorCode: '#29366D' },
        { name: 'Blue (SW900-615-M)', colorCode: '#184066' },
        { name: 'Frosty Blue (SW900-643-M)', colorCode: '#82A9B8' },
        { name: 'Moss Green (SW900-737-M)', colorCode: '#3E422A' },
        { name: 'Apple Green (SW900-745-M)', colorCode: '#659741' },
        { name: 'Pink (SW900-520-M)', colorCode: '#98364D' }
    ],
    Pearl: [
        { name: 'Satin White Pearl (SW900-117-S)', colorCode: '#D1CDC6' },
        { name: 'Pearl Light Green (SW900-777-S)', colorCode: '#8DC760' },
        { name: 'Pearl Dark Green (SW900-796-S)', colorCode: '#027B77' },
        { name: 'Gold Orange Pearlescent (SW900-326-S)', colorCode: '#EE963F' },
        { name: 'Gloss White Pearl (SW900-109-S)', colorCode: '#F9F9F9' }
    ],
    Chrome: [
        { name: 'Black (SF100-196-S)', colorCode: '' },
        { name: 'Silver (SF100-843-S)', colorCode: '' },
        { name: 'Red (SF100-474-S)', colorCode: '' },
        { name: 'Blue (SF100-256-S)', colorCode: '' },
        { name: 'Gold (SF100-604-S)', colorCode: '' },
        { name: 'Rose Gold (SF100-211-S)', colorCode: '' }
    ],
    Satin: [
        { name: 'Black (SW900-197-O)', colorCode: '#0B0B0B' },
        { name: 'Grey (SW900-833-O)', colorCode: '#696B6A' },
        { name: 'Carmine Red (SW900-438-O)', colorCode: '#98090F' },
        { name: 'Dark Blue (SW900-682-O)', colorCode: '#01338F' },
        { name: 'Light Blue (SW900-633-O)', colorCode: '#0098D2' },
        { name: 'Jade (SW900-7295-0)', colorCode: '#BCCDC2' },
        { name: 'Khaki Green (SW900-712-O)', colorCode: '#616358' },
        { name: 'Yellow (SW900-224-O)', colorCode: '#EFBE00' },
        { name: 'Bubblegum Pink (SW900-514-O)', colorCode: '#D5739E' },
        { name: 'White (SW900-116-O)', colorCode: '#E8E8E6' }
    ],
    Satin_Metallic: [
        { name: 'Black Rock Grey (SW900-823-M)', colorCode: '#373634' },
        { name: 'Dark Grey (SW900-854-M)', colorCode: '#3B393C' },
        { name: 'Dark Basalt (SW900-871-M)', colorCode: '#504941' },
        { name: 'Silver (SW900-805-M)', colorCode: '#7B7B7B' },
        { name: 'Purple (SW900-566-M)', colorCode: '#3D2C32' },
        { name: 'Safari Gold (SW900-260-M)', colorCode: '#86670B' },
        { name: 'Flamingo Dance (SW900-5080-M)', colorCode: '#E8E3EA' }
    ]
};

export const brandTeckwrapHex = {
    Chrome: [
        { name: 'Ice Silver', sku: 'CSC01', colorCode: '#696973' },
        { name: 'Graphite Grey', sku: 'CSC03', colorCode: '#353537' },
        { name: 'Shadow Red', sku: 'CSC04', colorCode: '#6A0E09' },
        { name: 'Dark Purple', sku: 'CSC05', colorCode: '#511C4A' },
        { name: 'Shadow Blue', sku: 'CSC06', colorCode: '#064166' },
        { name: 'Dark Green', sku: 'CSC07', colorCode: '#02490F' },
        { name: 'Copper Brown', sku: 'CSC08', colorCode: '#C84603' },
        { name: 'Super Silver (Mirror)', sku: 'CMC01', colorCode: '#D2D2D2' }
    ],
    Gloss: [
        { name: 'Deep Blue', sku: 'RB02-HD', colorCode: '#012475' },
        { name: 'Passionate Purple', sku: 'RB04-HD', colorCode: '#9D226F' },
        { name: 'Acid Lime', sku: 'RB07-HD', colorCode: '#B3C100' },
        { name: 'Coral Peach', sku: 'RB08-HD', colorCode: '#F85F55' },
        { name: 'Caribbean Blue', sku: 'RB09-HD', colorCode: '#49C4ED' },
        { name: 'Dark Platinum', sku: 'RB12-HD', colorCode: '#35353D' },
        { name: 'Ash Grey', sku: 'RB13-HD', colorCode: '#514545' },
        { name: 'Sea Turquoise', sku: 'RB16-HD', colorCode: '#05ACCD' },
        { name: 'Ocean Green', sku: 'RB18-HD', colorCode: '#0F7E53' },
        { name: 'Deep Orange', sku: 'RB19-HD', colorCode: '#FB6720' },
        { name: 'Midnight Purple', sku: 'RB20-HD', colorCode: '#421FB1' },
        { name: 'Kelly Green', sku: 'RB22-HD', colorCode: '#89D76C' },
        { name: 'Golden Yellow', sku: 'RB25-HD', colorCode: '#FF9503' },
        { name: 'Ruby Green', sku: 'RB26-HD', colorCode: '#015F20' },
        { name: 'Arctic Silver', sku: 'RB27-HD', colorCode: '#949BA1' },
        { name: 'Vibrant Nickel', sku: 'RB28-HD', colorCode: '#504E4F' },
        { name: 'Grau Pearl', sku: 'RB30-HD', colorCode: '#728493' },
        { name: 'Silver Fern', sku: 'RB31-HD', colorCode: '#B5B1A5' },
        { name: 'Deep Onix', sku: 'RB32-HD', colorCode: '#929680' },
        { name: 'Dolomite Silver', sku: 'RB33-HD', colorCode: '#C5C3C6' },
        { name: 'Wilderness Green', sku: 'RB35-HD', colorCode: '#807B64' },
        { name: 'Palladian Blue', sku: 'RB36-HD', colorCode: '#8C9894' },
        { name: 'Phantom Green', sku: 'RB37-HD', colorCode: '#424D21' },
        { name: 'Deep Purple Blue', sku: 'RB38-HD', colorCode: '#4E5373' },
        { name: 'Dragon Green', sku: 'RB39-HD', colorCode: '#3B533E' },
        { name: 'Titanium Violet', sku: 'RB40-HD', colorCode: '#383048' },
        { name: 'Gloss Green Black', sku: 'HM07-HD', colorCode: '#1A534A' },
        { name: 'Black Cherry Ice', sku: 'HM08-HD', colorCode: '#412035' },
        { name: 'Black Gold', sku: 'HM09-HD', colorCode: '#9E4F03' },
        { name: 'Burgundy Black', sku: 'HM10-HD', colorCode: '#593041' },
        { name: 'Sonoma Green', sku: 'HM12-HD', colorCode: '#35793B' },
        { name: 'Sherwood Green', sku: 'HM14-HD', colorCode: '#023239' },
        { name: 'Copper Bronze', sku: 'HM15-HD', colorCode: '#644540' },
        { name: 'Antique Green', sku: 'HM16-HD', colorCode: '#6D7E6E' },
        { name: 'Gloss Coal Black', sku: 'MT01-HD', colorCode: '#1D1B17' },
        { name: 'Pink Sakura', sku: 'SL01-HD', colorCode: '#F6AEBA' },
        { name: 'Royal Purple', sku: 'SL07-HD', colorCode: '#897EB7' }
    ],
    Matte: [
        { name: 'Satin Perl White', sku: 'ECH01', colorCode: '#CCCEC7' },
        { name: 'Gunsmoke Grey', sku: 'ECH02', colorCode: '#726E64' },
        { name: 'Charcoal Grey', sku: 'ECH03', colorCode: '#757575' },
        { name: 'Navy Black', sku: 'ECH15', colorCode: '#18171C' },
        { name: 'Hornet Yellow', sku: 'ECH16', colorCode: '#C29C00' },
        { name: 'Bond Gold', sku: 'ECH17', colorCode: '#5F5836' },
        { name: 'Forest Green', sku: 'ECH19', colorCode: '#334B45' },
        { name: 'Dark Platinum', sku: 'ECH21', colorCode: '#2F2E33' },
        { name: 'Cherry Blossom Pink', sku: 'ECH22', colorCode: '#F8A5B9' },
        { name: 'Matte Coal Black', sku: 'MT01', colorCode: '#323037' },
        { name: 'Ultimate Black', sku: 'CG01-HD', colorCode: '#3D3B3C' },
        { name: 'Super White', sku: 'CG02-HD', colorCode: '#EAEAEA' },
        { name: 'Amazon Grey', sku: 'CG03-HD', colorCode: '#758083' },
        { name: 'Racing Red', sku: 'CG06-HD', colorCode: '#FB1318' },
        { name: 'Tiffany', sku: 'CG11-HD', colorCode: '#04CFC5' },
        { name: 'Sunflower Yellow', sku: 'CG12-HD', colorCode: '#FFB400' },
        { name: 'Slate Grey', sku: 'CG16-HD', colorCode: '#B1ADB4' },
        { name: 'Vibrant Blue', sku: 'CG57-HD', colorCode: '#0389DF' },
        { name: 'Millennial Pink', sku: 'CG19-HD', colorCode: '#E2A9AF' },
        { name: 'Battleship Grey', sku: 'CG20-HD', colorCode: '#908C8D' },
        { name: 'Rolling Sea', sku: 'CG21-HD', colorCode: '#0097D1' },
        { name: 'China Blue', sku: 'CG22-HD', colorCode: '#8DA8D5' },
        { name: 'Mossy Green', sku: 'CG23-HD', colorCode: '#A19A8A' },
        { name: 'Lava Orange', sku: 'CG24-HD', colorCode: '#FE4C31' },
        { name: 'Chelsea Rose', sku: 'CG25-HD', colorCode: '#F3B2B0' },
        { name: 'Ivory Cream', sku: 'CG26-HD', colorCode: '#E2CCB6' },
        { name: 'True Nardo Grey', sku: 'CG27-HD', colorCode: '#9C9899' },
        { name: 'Yacht Blue', sku: 'CG28-HD', colorCode: '#9BCEDF' },
        { name: 'Khaki Green', sku: 'CG29-HD', colorCode: '#847744' },
        { name: 'Pale Celadon', sku: 'CG30-HD', colorCode: '#BBBCB7' },
        { name: 'French Olive', sku: 'CG31-HD', colorCode: '#7D9C59' },
        { name: 'Amphibian Green', sku: 'CG32-HD', colorCode: '#00553C' },
        { name: 'Sorbet Pink', sku: 'CG59-HD', colorCode: '#F0265F' },
        { name: 'Vanilla Mist', sku: 'CG60-HD', colorCode: '#E2DED2' },
        { name: 'Baby Blue', sku: 'CG58-HD', colorCode: '#7495C2' },
        { name: 'Amber Rose', sku: 'CG36-HD', colorCode: '#FD8470' },
        { name: 'Bali Blue', sku: 'CG37-HD', colorCode: '#ABC6CA' },
        { name: 'British Racing Green', sku: 'CG38-HD', colorCode: '#357F7A' },
        { name: 'Monsoon Green', sku: 'CG39-HD', colorCode: '#A8BFB2' },
        { name: 'Tangerine Orange', sku: 'CG40-HD', colorCode: '#F64902' },
        { name: 'Gecko Green', sku: 'CG41-HD', colorCode: '#98CD00' },
        { name: 'Grape Green', sku: 'CG42-HD', colorCode: '#BEB732' },
        { name: 'Louvre Yellow', sku: 'CG43-HD', colorCode: '#DEBB00' },
        { name: 'Sunray Yellow', sku: 'CG44-HD', colorCode: '#DEA604' },
        { name: 'Amberwave', sku: 'CG45-HD', colorCode: '#F8D8A9' },
        { name: 'Sahara Beige', sku: 'CG46-HD', colorCode: '#F0D1BC' },
        { name: 'Vintage Grey', sku: 'CG47-HD', colorCode: '#ADAEB0' },
        { name: 'Spanish Lavender', sku: 'CG48-HD', colorCode: '#CDBDE2' },
        { name: 'Berry Red', sku: 'CG49-HD', colorCode: '#D93B78' },
        { name: 'Strawberry Milk', sku: 'CG50-HD', colorCode: '#EAD6CB' },
        { name: 'Camouflage Green', sku: 'CG51-HD', colorCode: '#394231' },
        { name: 'Leather Beige', sku: 'CG52-HD', colorCode: '#CAA468' },
        { name: 'Cool Blue', sku: 'CG53-HD', colorCode: '#96BFCF' },
        { name: 'Papaya Orange', sku: 'CG54-HD', colorCode: '#F69D35' },
        { name: 'Wild Dove', sku: 'CG55-HD', colorCode: '#807C7B' },
        { name: 'Flamingo Pink', sku: 'CG56-HD', colorCode: '#D68187' },
        { name: 'Top Coated Super Black', sku: 'CG01-SH', colorCode: '#282627' },
        { name: 'Top Coated Moss Green', sku: 'CG23-SH', colorCode: '#8C8B77' },
        { name: 'Top Coated Vintage Grey', sku: 'CG47-SH', colorCode: '#828483' },
        { name: 'Black', sku: 'CG01', colorCode: '#181C1F' }
    ],
    Super_Matte: [
        { name: 'Black', sku: 'CM01M', colorCode: '#333333' },
        { name: 'White', sku: 'CM02', colorCode: '#ECEDF3' },
        { name: 'Military Green', sku: 'CM09', colorCode: '#606644' },
        { name: 'Sandy Black', sku: 'CM01-MS', colorCode: '#4F453C' },
        { name: 'Sable Black', sku: 'TC01', colorCode: '#171818' },
        { name: 'Piniengruen Pearl', sku: 'TC02', colorCode: '#606755' },
        { name: 'Deep Black', sku: 'SCM01', colorCode: '#262729' },
        { name: 'Alaska White', sku: 'SCM02', colorCode: '#DAD8DD' },
        { name: 'Lizard Grey', sku: 'SCM23', colorCode: '#727467' },
        { name: 'Nickel Grey', sku: 'SCM27', colorCode: '#71737A' },
        { name: 'Vanilla Cream', sku: 'SCM26-R', colorCode: '#E9D6C5' },
        { name: 'Autumn Blaze', sku: 'SCM36', colorCode: '#FF8578' },
        { name: 'Granite Grey', sku: 'SCM47', colorCode: '#B0ABAF' },
        { name: 'Pearl Black', sku: 'CM15', colorCode: '#27282C' },
        { name: 'Raven Black', sku: 'CM14', colorCode: '#131217' },
        { name: 'Grainy Black', sku: 'CM02-MS', colorCode: '#2D2C33' }
    ],
    Mirror_Chrome: [
        { name: 'White Gold', sku: 'CHM01-HD', colorCode: '#797979' },
        { name: 'Yellow Gold', sku: 'CHM02-HD', colorCode: '#EFA114' },
        { name: 'Cherry Red', sku: 'CHM04-HD', colorCode: '#E0373F' },
        { name: 'Rose Gold', sku: 'CHM03-HD', colorCode: '#6C3A3E' },
        { name: 'Jet Black', sku: 'CHM10-HD', colorCode: '#4E444F' },
        { name: 'Solar Gold', sku: 'CHM21-HD', colorCode: '#E2C04F' },
        { name: 'Crystal Chrome', sku: 'CHM22-HD', colorCode: '#CDCDCD' },
        { name: 'Inferno Red', sku: 'CHM24-HD', colorCode: '#D30625' },
        { name: 'Nova Blue', sku: 'CHM26-HD', colorCode: '#2A1C76' }
    ],
    Satin_Chrome: [
        { name: 'Crimson Red', sku: 'VCH401-S', colorCode: '#9A1915' },
        { name: 'Velvet Blue', sku: 'VCH402-S', colorCode: '#0A2C83' },
        { name: 'Concord Grape', sku: 'VCH403-S', colorCode: '#571B51' },
        { name: 'Hot Pink', sku: 'VCH404-S', colorCode: '#AF2053' },
        { name: 'Emerald Green', sku: 'VCH405-S', colorCode: '#09A79A' },
        { name: 'Golden Yellow', sku: 'VCH408-S', colorCode: '#906600' },
        { name: 'Gunmetal Grey', sku: 'VCH410-S', colorCode: '#6A6068' },
        { name: 'Super Silver Sage', sku: 'VCH411-S', colorCode: '#D1CCD3' },
        { name: 'Lemon Yellow', sku: 'VCH412-S', colorCode: '#C0BC00' },
        { name: 'Violet Purple', sku: 'VCH416-S', colorCode: '#4423A5' },
        { name: 'Carmine Red', sku: 'VCH417-S', colorCode: '#DC0100' },
        { name: 'Autumn Orange', sku: 'VCH418-S', colorCode: '#F56107' },
        { name: 'Deep Cobalt', sku: 'VCH419-S', colorCode: '#131F35' },
        { name: 'Lapis Blue', sku: 'VCH420-S', colorCode: '#101867' },
        { name: 'Antique Rose', sku: 'VCH421-S', colorCode: '#B77A78' },
        { name: 'Sangria Red', sku: 'VCH422-S', colorCode: '#B31319' },
        { name: 'Gable Green', sku: 'VCH423-S', colorCode: '#006C43' }
    ],
    Satin_Metallic: [
        { name: 'Dark Grey Silk', sku: 'HM01', colorCode: '#262228' },
        { name: 'Black Silver', sku: 'HM02-R', colorCode: '#65544C' },
        { name: 'Matte Green Black Silk', sku: 'HM07', colorCode: '#1A300D' },
        { name: 'Greenfinch Gold', sku: 'HM09', colorCode: '#736428' },
        { name: 'Mineral Grey', sku: 'SMT01', colorCode: '#796D59' },
        { name: 'Burnt Maroon', sku: 'SMT02', colorCode: '#65241A' },
        { name: 'Venetian Violet', sku: 'SMT03', colorCode: '#532C5F' },
        { name: 'Boysenberry Black', sku: 'SMT04', colorCode: '#555C6E' },
        { name: 'Green Mantle', sku: 'SMT05', colorCode: '#41554A' },
        { name: 'Apollo Grey', sku: 'SMT06', colorCode: '#3E3C38' },
        { name: 'Rasant Blue', sku: 'SMT07', colorCode: '#4E73D3' },
        { name: 'Admiral Blue', sku: 'SMT08', colorCode: '#1A227C' },
        { name: 'Onyx Grey', sku: 'SMT09', colorCode: '#594B40' },
        { name: 'Solar Orange', sku: 'SMT10', colorCode: '#FF7503' },
        { name: 'Surf Blue', sku: 'SMT11', colorCode: '#77B5E9' },
        { name: 'Paradise Green', sku: 'SMT12', colorCode: '#6ED56A' },
        { name: 'Pine Green', sku: 'SMT13', colorCode: '#012921' },
        { name: 'Lawn Green', sku: 'SMT14', colorCode: '#9DCE1C' },
        { name: 'Flame Red', sku: 'SMT15', colorCode: '#930012' },
        { name: 'Jewel Green', sku: 'SMT16', colorCode: '#004549' },
        { name: 'Copper Orange', sku: 'SMT17R', colorCode: '#B24302' },
        { name: 'Velour Red', sku: 'SMT18R', colorCode: '#4E1D21' },
        { name: 'Silver Blue', sku: 'SMT19', colorCode: '#5D6773' }
    ]
};

export const brandVvividHex = {
    Matte: [
        { name: 'Combat Pearl Gray', colorCode: '#D0D0D0' },
        { name: 'Viper Lime Metallic', colorCode: '#A9C246' },
        { name: 'Blood Orange Metallic', colorCode: '#D54837' },
        { name: 'Metallic Miami Teal', colorCode: '#22D4BE' },
        { name: 'Rally Beige', colorCode: '#E0D7C5' },
        { name: 'Midnight Purple (Porsche 911 GT3 Purple)', colorCode: '#9F7BE6' },
        { name: 'Metallic Daytona Yellow', colorCode: '#DFE465' },
        { name: 'Miami Teal', colorCode: '#05DBCF' },
        { name: 'Suzuka Ice Grey', colorCode: '#C8C8C8' },
        { name: 'Metallic Lava Red', colorCode: '#C44B4D' },
        { name: 'Metallic Orange', colorCode: '#F4822F' },
        { name: 'Metallic Blue (Ghost)', colorCode: '#2A77BA' },
        { name: 'Metallic Black (Ghost)', colorCode: '#3E403F' },
        { name: 'Metallic Copper Rust (Ghost)', colorCode: '#B76B49' },
        { name: 'Metallic Green (Ghost)', colorCode: '#8EC271' },
        { name: 'Metallic Military Green (Ghost)', colorCode: '#969C83' },
        { name: 'Metallic Navy Blue (Ghost)', colorCode: '#5D75AF' },
        { name: 'Metallic Purple (Ghost)', colorCode: '#73589D' },
        { name: 'Black Matte', colorCode: '#474747' },
        { name: 'Metallic Charcoal', colorCode: '#84868A' },
        { name: 'Desert Gold Matte', colorCode: '#977E3A' },
        { name: 'Army Brown Matte', colorCode: '#80604C' },
        { name: 'Military Green Matte', colorCode: '#5E6950' },
        { name: 'Lime Matte', colorCode: '#59BE5C' },
        { name: 'Electric Lime Matte', colorCode: '#B4C232' },
        { name: 'Orange Matte', colorCode: '#E08444' },
        { name: 'Magenta Matte', colorCode: '#B82B7D' },
        { name: 'Pastel Pink Matte', colorCode: '#F58DC2' }
    ],
    Gloss: [
        { name: 'Nightshade Goblin Blue', colorCode: '#016D6D' },
        { name: 'Galaxy Purple', colorCode: '#593E73' },
        { name: 'Joker Purple', colorCode: '#BA3278' },
        { name: 'Galaxy Nardo Grey', colorCode: '#7F8185' },
        { name: 'Nightshade Purple', colorCode: '#9C668D' },
        { name: 'Psycho Blue', colorCode: '#356295' },
        { name: 'Psycho Copper', colorCode: '#C66964' },
        { name: 'Psycho Purple', colorCode: '#60418A' },
        { name: 'Super Hero Blue', colorCode: '#3347B0' },
        { name: 'Poison Purple Gloss', colorCode: '#5423B2' },
        { name: 'Demon Black Gloss (Nebula)', colorCode: '#5F3131' },
        { name: 'Black Pearl', colorCode: '#4D4E4B' },
        { name: 'Midnight Purple (Porsche 911 GT3 Purple)', colorCode: '#6A53A3' },
        { name: 'Rally Beige', colorCode: '#B4ADA2' },
        { name: 'Slate Grey (Grigio Telesto)', colorCode: '#6F717B' },
        { name: 'Miami Teal', colorCode: '#43D0D1' },
        { name: 'Muscular Magenta', colorCode: '#DA3D90' },
        { name: 'Smurf Blue (Riviera Porsche GT3 Blue)', colorCode: '#3883E0' },
        { name: 'Rosso Corsa Red', colorCode: '#C33F40' },
        { name: 'Viper Lime Green (fluo)', colorCode: '#B4C83F' },
        { name: 'Liquid Metal Pink', colorCode: '#9C606A' },
        { name: 'Liquid Metal Green', colorCode: '#1E8518' },
        { name: 'Liquid Metal Purple', colorCode: '#851690' },
        { name: 'Black', colorCode: '#3F3F3F' },
        { name: 'Metallic Sparkle Black', colorCode: '#373737' },
        { name: 'Metallic Sparkle White', colorCode: '#EBEBEB' },
        { name: 'White', colorCode: '#F7F7F7' },
        { name: 'Space Pearl White', colorCode: '#CDD9E2' },
        { name: 'Liquid Metal Aqua Blue', colorCode: '#376E94' },
        { name: 'Liquid Metal Blue', colorCode: '#2D49C2' },
        { name: 'Gloss Lime Green', colorCode: '#6CAD51' },
        { name: 'Liquid Metal Viper Lime Green', colorCode: '#9EB11F' },
        { name: 'Liquid Metal Yellow', colorCode: '#D5C846' },
        { name: 'Pastel Pink', colorCode: '#EFA2D1' }
    ],
    Chrome: [
        { name: 'Conform Chrome Silver', colorCode: '#D2D2D2' },
        { name: 'Conform Chrome Yellow', colorCode: '#CBBF33' },
        { name: 'Conform Chrome Gold', colorCode: '#A97C49' },
        { name: 'Conform Chrome Orange', colorCode: '#DE502D' },
        { name: 'Conform Chrome Red', colorCode: '#D71E3E' },
        { name: 'Conform Chrome Blue', colorCode: '#02619D' },
        { name: 'Conform Chrome Green', colorCode: '#21A102' }
    ]
};


export const brandAPAHex = {
    Gloss: [
        { name: 'URBAN IVORY', colorCode: '#E8DDAE' },
        { name: 'YELLOW', colorCode: '#EDB832' },
        { name: 'SIGNAL YELLOW', colorCode: '#FAB131' },
        { name: 'ORANGE', colorCode: '#FF6629' },
        { name: 'RED', colorCode: '#E03043' },
        { name: 'CORAL', colorCode: '#FF5653' },
        { name: 'KIRBY PINK', colorCode: '#FDA3AE' },
        { name: 'RUBYSTONE', colorCode: '#BE2A63' },
        { name: 'HALO LAVENDER', colorCode: '#9584BE' },
        { name: 'GULF BLUE', colorCode: '#9DB6C2' },
        { name: 'OPTIMUS BLUE', colorCode: '#9EAAC0' },
        { name: 'AREA 51', colorCode: '#72818F' },
        { name: 'CERULEAN BLUE', colorCode: '#288BC5' },
        { name: 'MIAMI BLUE', colorCode: '#328E8C' },
        { name: 'BIMINI TEAL', colorCode: '#326F69' },
        { name: 'PETROL BLUE', colorCode: '#395F68' },
        { name: 'OSLO BLUE', colorCode: '#1D5A6F' },
        { name: 'ROYAL BLUE', colorCode: '#224AA1' },
        { name: 'NAVY BLUE', colorCode: '#26263E' },
        { name: 'BLACK OLIVE', colorCode: '#4A482A' },
        { name: 'WARRIOR GREEN', colorCode: '#5C5A37' },
        { name: 'AURATIUM GREEN', colorCode: '#77815C' },
        { name: 'WASABI', colorCode: '#B4C89F' },
        { name: 'APPLE GREEN', colorCode: '#B8CE38' },
        { name: 'SANDSTORM', colorCode: '#988B68' },
        { name: 'STONE GREY', colorCode: '#8D8861' },
        { name: 'LUNAR ROCK', colorCode: '#808C7F' },
        { name: 'MANHATTAN GREY', colorCode: '#A8A7A6' },
        { name: 'RAINSTORM GREY', colorCode: '#7D7C7B' },
        { name: 'JET BLACK', colorCode: '#0A0A09' },
        { name: 'WHITE', colorCode: '#FFFFFE' },
        { name: 'Metal ELECTRIC SUNSET', colorCode: '#FF8825' },
        { name: 'Metal VOODOO PURPLE', colorCode: '#6C256A' },
        { name: 'Metal GALAXY BLUE', colorCode: '#141938' },
        { name: 'Metallic SPACE BLUE', colorCode: '#4A687C' },
        { name: 'Metal ALIEN\'S SOUP', colorCode: '#2985A2' },
        { name: 'Metal HAWAII MINT', colorCode: '#9AE7CA' },
        { name: 'Metal KRYPTONITE', colorCode: '#87A22C' },
        { name: 'Metal BRITISH GREEN', colorCode: '#1B3813' },
        { name: 'Metallic RACING GREEN', colorCode: '#2C3915' },
        { name: 'Metallic BILLIONAIRE GREEN', colorCode: '#484918' },
        { name: 'Metallic GARDEN GLOW', colorCode: '#5E603B' },
        { name: 'Metal CHAMPAGNE BRONZE', colorCode: '#D8BC7C' },
        { name: 'Metal COMET SILVER', colorCode: '#C3C3C0' },
        { name: 'Metal MIST SILVER', colorCode: '#9F9F92' },
        { name: 'Metal URBAN GREY', colorCode: '#585857' },
        { name: 'Metal DAYTONA GREY', colorCode: '#4E4E4A' }
    ],
    Satin: [
        { name: 'SOLID RED', colorCode: '#DA002E' },
        { name: 'KIRBY PINK', colorCode: '#FD99A7' },
        { name: 'HALO LAVENDER', colorCode: '#B588D2' },
        { name: 'BLACK OLIVE', colorCode: '#393716' },
        { name: 'SANDSTORM', colorCode: '#8F7F5B' },
        { name: 'DESERT KHAKI', colorCode: '#A59F95' },
        { name: 'LUNAR ROCK', colorCode: '#778376' },
        { name: 'RAINSTORM GREY', colorCode: '#7F7F7F' },
        { name: 'MANHATTAN GREY', colorCode: '#B2B2B2' },
        { name: 'BLACK', colorCode: '#1B1B1B' },
        { name: 'WHITE', colorCode: '#FFFFFF' }
    ],
    Matte: [
        { name: 'INDIGO BLUE', colorCode: '#62A4E5' },
        { name: 'BLACK', colorCode: '#161616' }
    ]
};


export const brandVinylFrogHex = {
    Metallic: [
        { name: 'Brown Gray', colorCode: '#7A7470' },
        { name: 'Dark Gray', colorCode: '#5A5B62' },
        { name: 'Galaxy Black', colorCode: '#0E0E0F' },
        { name: 'Black Rose', colorCode: '#24181A' },
        { name: 'Grape Purple', colorCode: '#451D4F' },
        { name: 'Deep Blue', colorCode: '#18265C' },
        { name: 'Cherry Red', colorCode: '#5D2C28' },
        { name: 'Passion Pink', colorCode: '#C69BA7' },
        { name: 'Golden Yellow', colorCode: '#ECAF24' },
        { name: 'Metal Silver', colorCode: '#898D90' },
        { name: 'Royal Green', colorCode: '#14251A' },
        { name: 'Frozen Berry', colorCode: '#968485' },
        { name: 'Mocha Brown', colorCode: '#1E140E' },
        { name: 'Metal Black', colorCode: '#050407' },
        { name: 'British Racing Green', colorCode: '#082A29' },
        { name: 'Vampire Red', colorCode: '#79191C' },
        { name: 'Tanzanite Blue', colorCode: '#141A31' },
        { name: 'Coal Ash', colorCode: '#353739' },
        { name: 'Gotland Green', colorCode: '#202825' },
        { name: 'Silver Lake Blue', colorCode: '#688DAE' },
        { name: 'Liquid Chrome', colorCode: '#9B9A9F' },
        { name: 'Liquid Silver', colorCode: '#808479' },
        { name: 'Rosewood Red', colorCode: '#44262C' },
        { name: 'Light Steel Blue', colorCode: '#6A7B83' },
        { name: 'Midnight Purple', colorCode: '#201C31' },
        { name: 'Midnight Gold', colorCode: '#2A2218' },
        { name: 'Dragon Blood', colorCode: '#9E1E26' },
        { name: 'Raspberry Red', colorCode: '#430717' },
        { name: 'Rufous Red', colorCode: '#421414' },
        { name: 'Pearl Blue', colorCode: '#073786' },
        { name: 'Cobalt Blue', colorCode: '#233168' },
        { name: 'Beacon Blue', colorCode: '#183556' },
        { name: 'Spanish Viridian', colorCode: '#0E3A3D' },
        { name: 'La Salle Green', colorCode: '#052E23' },
        { name: 'Bronze Orange', colorCode: '#AA6021' },
        { name: 'Champagne Gold', colorCode: '#7B694A' },
        { name: 'Copper', colorCode: '#663D1E' },
        { name: 'Unicorn Silver', colorCode: '#8F8F8F' },
        { name: 'Violet Gray', colorCode: '#443951' },
        { name: 'Beau Blue', colorCode: '#4B545F' },
        { name: 'Stone Gray', colorCode: '#414246' },
        { name: 'Dim Gray', colorCode: '#4A484A' },
        { name: 'Silver Gray', colorCode: '#444444' },
        { name: 'Champagne Silver', colorCode: '#7F7D7C' },
        { name: 'Glitter Champagne', colorCode: '#77735D' },
        { name: 'Everton Blue', colorCode: '#1F2E5B' },
        { name: 'Sacramento Green', colorCode: '#152A25' },
        { name: 'Glitter Black Blue', colorCode: '#23232C' },
        { name: 'District Green', colorCode: '#3C4B35' },
        { name: 'Bernina Gray', colorCode: '#69686D' },
        { name: 'Victoria Violet', colorCode: '#3E283D' },
        { name: 'Old Lavender', colorCode: '#4B3F48' },
        { name: 'Rubellite Purple', colorCode: '#5F1B34' },
        { name: 'Plum Purple', colorCode: '#2B0E15' },
        { name: 'Rich Maroon', colorCode: '#640542' },
        { name: 'Deep Sea Green Metallic', colorCode: '#015D5C' },
        { name: 'Majestic Dark Gray', colorCode: '#393F43' },
        { name: 'Majestic White', colorCode: '#D7D2D4' },
        { name: 'Majestic Black', colorCode: '#242326' },
        { name: 'Diamond White', colorCode: '#E9E7E8' },
        { name: 'Glitter Black', colorCode: '#2C2C2E' },
        { name: 'Diamond Purple Blue', colorCode: '#093F6D' },
        { name: 'Pearl Blue Gold', colorCode: '#CECEC9' },
        { name: 'Pearl White', colorCode: '#EDE9E6' },
        { name: 'Dark Gray', colorCode: '#5A5A5A' },
        { name: 'Metallic Pearl Black', colorCode: '#151517' },
        { name: 'Titanium Gray', colorCode: '#65676B' },
        { name: 'Pearl Baby Pink', colorCode: '#E3B9BD' },
        { name: 'Neon Yellow', colorCode: '#B7C841' },
        { name: 'Neon Green', colorCode: '#5AAD51' },
        { name: 'Neon Orange', colorCode: '#D58031' },
        { name: 'Neon Ice Blue', colorCode: '#5EB8C3' },
        { name: 'Neon Pink', colorCode: '#C66A60' },
        { name: 'Gray Pink', colorCode: '#8C818E' },
        { name: 'Dark Gray Blue', colorCode: '#87A9C4' },
        { name: 'Gray Purple', colorCode: '#9C98AE' },
        { name: 'Magic Gray Green', colorCode: '#9796AB' },
        { name: 'Silver Gray Blue', colorCode: '#C3BDCA' },
        { name: 'Pink White', colorCode: '#DFD3D7' },
        { name: 'Black Red', colorCode: '#170C0D' }
    ],
    Matte: [
        { name: 'Black Pearl', colorCode: '#0D0C0F' },
        { name: 'Satin Black', colorCode: '#121418' },
        { name: 'Military Green', colorCode: '#37442B' },
        { name: 'Gunmetal Gray', colorCode: '#353130' },
        { name: 'AMG Gray', colorCode: '#151515' },
        { name: 'Black Olive', colorCode: '#191F16' },
        { name: 'Silk Black', colorCode: '#0E0E10' },
        { name: 'Silk Gray Blue', colorCode: '#4D585D' },
        { name: 'Russian Violet', colorCode: '#402B3D' },
        { name: 'Metallic Black Purple', colorCode: '#1E1F28' },
        { name: 'Metallic Black Blue', colorCode: '#272931' },
        { name: 'Metallic Hunter Green', colorCode: '#202B2C' },
        { name: 'Metallic Gray', colorCode: '#4A4C4B' },
        { name: 'Gunmetal Purple', colorCode: '#535159' }
    ],
    Chrome: [
        { name: 'Prismatic Red', colorCode: '#7C1C2C' },
        { name: 'Chocolate Cosmos Red', colorCode: '#260F11' },
        { name: 'Silk Ultramarine', colorCode: '#1B2E73' },
        { name: 'Saint Patrick Blue', colorCode: '#262845' },
        { name: 'Silk Prussian Blue', colorCode: '#202B3C' },
        { name: 'Silk Green', colorCode: '#294338' },
        { name: 'Silk Copper', colorCode: '#6D4223' },
        { name: 'Silk Rose Gold', colorCode: '#AC7D86' },
        { name: 'Titanium Sliver', colorCode: '#828188' },
        { name: 'Opal White', colorCode: '#C8B5F2' },
        { name: 'Opal Black', colorCode: '#BD6A01' },
        { name: 'Mirror Silver', colorCode: '#818181' },
        { name: 'Mirror Gold', colorCode: '#906800' }
    ],
    HighGloss: [
        { name: 'Paint Black', colorCode: '#0D0C0F' },
        { name: 'Piano Black', colorCode: '#0C0B0E' },
        { name: 'Crystal White', colorCode: '#F8F2F7' },
        { name: 'Bright Gray', colorCode: '#C4C2C2' },
        { name: 'Ferrari Red', colorCode: '#DB392B' },
        { name: 'Yellow', colorCode: '#CAB424' },
        { name: 'Tiffany', colorCode: '#72B7B3' },
        { name: 'Sky Blue', colorCode: '#70C1E2' },
        { name: 'Baby Pink', colorCode: '#DAADB7' },
        { name: 'Nardo Gray', colorCode: '#757371' },
        { name: 'Rouge Pink', colorCode: '#D99DA6' },
        { name: 'Orange', colorCode: '#E46F39' },
        { name: 'Miami Blue', colorCode: '#147997' },
        { name: 'China Blue', colorCode: '#617F9A' },
        { name: 'Yacht Blue', colorCode: '#A1B6C4' },
        { name: 'Khaki Green', colorCode: '#828478' },
        { name: 'Reddish Orange', colorCode: '#CF3421' },
        { name: 'Jade Green', colorCode: '#B1C2BD' },
        { name: 'Glacier Blue', colorCode: '#C7E5E6' },
        { name: 'Air Force Blue', colorCode: '#788A96' },
        { name: 'Ivory White', colorCode: '#E6E0CB' },
        { name: 'Lavender Purple', colorCode: '#806BA6' },
        { name: 'Reseda Green', colorCode: '#3C3819' },
        { name: 'Pistachio Green', colorCode: '#A9B29A' },
        { name: 'Periwinkle Purple', colorCode: '#C6BCDB' },
        { name: 'Gentle Gray', colorCode: '#A5A6A1' },
        { name: 'Pale Pink', colorCode: '#E1C5C6' },
        { name: 'Gainsboro Gray', colorCode: '#ABA7A4' },
        { name: 'Concord Buff', colorCode: '#E0C4A2' },
        { name: 'Decent Burlywood', colorCode: '#D4B47B' },
        { name: 'Ruby Star', colorCode: '#991D56' },
        { name: 'Purple Pizzazz', colorCode: '#C42C68' },
        { name: 'Chartreuse Yellow', colorCode: '#DADE56' },
        { name: 'Racing Yellow', colorCode: '#E4C72B' },
        { name: 'Vintage Racing Green', colorCode: '#233922' },
        { name: 'Laguna Blue', colorCode: '#01436D' },
        { name: 'Pink Gray', colorCode: '#CBBBAF' },
        { name: 'Simply White', colorCode: '#EAE6D7' },
        { name: 'Mclaren Orange', colorCode: '#FE9D00' },
        { name: 'Misty Lavender', colorCode: '#D6CAD0' },
        { name: 'Pink lavender', colorCode: '#C5A8B4' },
        { name: 'Warm Gray', colorCode: '#8F828B' },
        { name: 'Dodger Blue', colorCode: '#0A6BCF' },
        { name: 'Purplish Grey', colorCode: '#0A6BCF' },
        { name: 'Rifle Green', colorCode: '#505243' },
        { name: 'Piggy Pink', colorCode: '#EACEC4' },
        { name: 'Jamaican Aqua', colorCode: '#AFD8CD' },
        { name: 'Glossy White Gold', colorCode: '#E4E3E9' },
        { name: 'Glossy White Red', colorCode: '#D7D9D9' },
        { name: 'Glossy White Purple', colorCode: '#E6E4E0' },
        { name: 'Glossy White Blue', colorCode: '#E3DFD7' },
        { name: 'Glossy Pearl White', colorCode: '#E7E3E0' },
        { name: 'CarbonShield Ultra', colorCode: '#222327' },
        { name: 'Crystal Black', colorCode: '#151517' },
        { name: 'Crystal White', colorCode: '#F8F2F7' },
        { name: 'China Blue', colorCode: '#617F9A' },
        { name: 'Lavender Purple', colorCode: '#806BA6' },
        { name: 'Nardo Gray', colorCode: '#757371' },
        { name: 'Black Rose', colorCode: '#24181A' },
        { name: 'Grape Purple', colorCode: '#451D4F' },
        { name: 'Vampire Red', colorCode: '#79191C' },
        { name: 'Midnight Purple', colorCode: '#201C31' },
        { name: 'Black Red', colorCode: '#170C0D' },
        { name: 'Neon Green', colorCode: '#5AAD51' },
        { name: 'Neon Ice Blue', colorCode: '#5EB8C3' },
        { name: 'Gray Purple', colorCode: '#9C98AE' },
        { name: 'Glossy Black', colorCode: '#130F12' }
    ]
};

export const brandHexisHX30000 = {
    Gloss: [
        { name: 'Nacre White Gloss', colorCode: '#E0E5EB' },
        { name: 'Pearl White Gloss', colorCode: '' },
        { name: 'Redcurrant Red Gloss', colorCode: '' },
        { name: 'Chameleon Grey Gloss', colorCode: '#8C8C8C' },
        { name: 'Neon Blue Gloss', colorCode: '' },
        { name: 'Austral Sea Iridescent Gloss', colorCode: '' },
        { name: 'Boreal Forest Iridescent Gloss', colorCode: '#2E4A2F' },
        { name: 'White Rainbow Gloss', colorCode: '#FFFFFF' },
        { name: 'Meteorite Grey Rainbow Gloss', colorCode: '' }
    ],
    Matte: [
        { name: 'Redcurrant Red Matte', colorCode: '#7E354D' },
        { name: 'Boston Green Matte', colorCode: '#006442' },
        { name: 'Golden Black Matte', colorCode: '#1C1B17' }
    ]
};



export const brandHexisHX20000 = {
    Gloss: [
        { name: 'Polar White Gloss', colorCode: '' },
        { name: 'Lapland White Gloss', colorCode: '#F4F7F7' },
        { name: 'Glacier White Gloss', colorCode: '' },
        { name: 'Pack Ice White Gloss', colorCode: '#E8EEF0' },
        { name: 'Saturn White Gloss', colorCode: '#F2EEE9' },
        { name: 'Taxi Beige Gloss', colorCode: '#E8D9B3' },
        { name: 'Ivory Gloss', colorCode: '#F6E9D8' },
        { name: 'Ashen Beige Metallic Gloss', colorCode: '#C1B097' },
        { name: 'Zeus Gold Gloss', colorCode: '#D4AF37' },
        { name: 'Honey Yellow Gloss', colorCode: '#F1C232' },
        { name: 'Fluorescent Orange Gloss', colorCode: '#FF5B00' },
        { name: 'Urban Orange Gloss', colorCode: '#F16529' },
        { name: 'Mandarin Red Gloss', colorCode: '#E54B2C' },
        { name: 'Zenith Orange Gloss', colorCode: '#FF6B1A' },
        { name: 'Fluorescent Red Gloss', colorCode: '#FF1744' },
        { name: 'Red Embers Gloss', colorCode: '#A62C2B' },
        { name: 'Red Racing Gloss', colorCode: '#CC0000' },
        { name: 'Ruby Red Gloss', colorCode: '#AA0114' },
        { name: 'Blood Red Gloss', colorCode: '#7A0C0C' },
        { name: 'Garnet Red Gloss', colorCode: '#8B0000' },
        { name: 'Jellybean Pink Gloss', colorCode: '#F77FBE' },
        { name: 'Pink Candy Gloss', colorCode: '#FF69B4' },
        { name: 'Indian Pink Gloss', colorCode: '#F6A5C0' },
        { name: 'Fuchsia Gloss', colorCode: '#C154C1' },
        { name: 'Plum Violet Gloss', colorCode: '#673147' },
        { name: 'Damask Violet Gloss', colorCode: '#A64CA6' },
        { name: 'Elderberry Purple Gloss', colorCode: '#54194E' },
        { name: 'Byzantine Violet Gloss', colorCode: '#702963' },
        { name: 'Jazz Blue Gloss', colorCode: '#1A4BA0' },
        { name: 'Polaris Bleu Gloss', colorCode: '#3E6D9C' },
        { name: 'Niagara Blue Gloss', colorCode: '#3B83BD' },
        { name: 'Yas Marina Blue Gloss', colorCode: '#4A90E2' },
        { name: 'Montpellier Blue Gloss', colorCode: '#2C4E84' },
        { name: 'Apollo Blue Gloss', colorCode: '#003366' },
        { name: 'Curacao Blue Gloss', colorCode: '#1CA9C9' },
        { name: 'Sapphire Blue Gloss', colorCode: '#0F52BA' },
        { name: 'Night Blue Met Gloss', colorCode: '#1A2B4C' },
        { name: 'Pacific Blue Gloss', colorCode: '#1CA9E6' },
        { name: 'Triton Blue Gloss', colorCode: '#0162A7' },
        { name: 'Night Blue Gloss', colorCode: '#191970' },
        { name: 'Firmament Blue Gloss', colorCode: '#003399' },
        { name: 'Abyssal Blue Gloss', colorCode: '#001F3F' },
        { name: 'Ti Blue Gloss', colorCode: '#2A52BE' },
        { name: 'South Sea Blue Gloss', colorCode: '#3BB9FF' },
        { name: 'Fjord Blue Gloss', colorCode: '#436B95' },
        { name: 'Pigeon Blue Gloss', colorCode: '#7285A5' },
        { name: 'Fluorescent Green Gloss', colorCode: '#39FF14' },
        { name: 'Toxic Green Gloss', colorCode: '#00FF66' },
        { name: 'Light Green Gloss', colorCode: '#90EE90' },
        { name: 'Wasabi Green Gloss', colorCode: '#A8C545' },
        { name: 'Apple Green Gloss', colorCode: '#8DB600' },
        { name: 'Drosera Green Gloss', colorCode: '#228B22' },
        { name: 'Emerald Green Gloss', colorCode: '#046307' },
        { name: 'Mountain Peak White Gloss', colorCode: '#F5F7F6' },
        { name: 'Cloud Grey Gloss', colorCode: '#B7BCC8' },
        { name: 'Silver Gloss', colorCode: '#C0C0C0' },
        { name: 'Meteorite Grey Gloss', colorCode: '#555D61' },
        { name: 'Bronze Grey Gloss', colorCode: '#6E5A46' },
        { name: 'Pleiades Grey Gloss', colorCode: '#6D7178' },
        { name: 'Dust Grey Gloss', colorCode: '#999999' },
        { name: 'Pearl Grey Gloss', colorCode: '#D4D8DD' },
        { name: 'Elephant Grey Gloss', colorCode: '#8B8C89' },
        { name: 'Aston Grey Gloss', colorCode: '#5E5E60' },
        { name: 'Shark Grey Gloss', colorCode: '#5B616A' },
        { name: 'Dark Grey Gloss', colorCode: '#3E3E3E' },
        { name: 'Cinder Rose Metal Gloss', colorCode: '#7D4A58' },
        { name: 'Marrakesh Brown Gloss', colorCode: '#604134' },
        { name: 'Havana Brown Gloss', colorCode: '#5B3A29' },
        { name: 'Brown Gloss', colorCode: '#4E342E' },
        { name: 'Coffee Brown Gloss', colorCode: '#4B3621' },
        { name: 'Vampire Black Gloss', colorCode: '#0A0A0A' },
        { name: 'Coal Black Gloss', colorCode: '#1C1C1C' },
        { name: 'Deep Black Gloss', colorCode: '#000000' },
        { name: 'Mystery Black Gloss', colorCode: '#0D0C0C' }
    ],
    Satin: [
        { name: 'Nacre White Satin', colorCode: '#E0E5EB' },
        { name: 'Fluorescent Red Satin', colorCode: '#FF1744' },
        { name: 'Red Alu Satin', colorCode: '#B22222' },
        { name: 'Pink Lady Satin', colorCode: '#FF69B4' },
        { name: 'Ara Blue Metallic Satin', colorCode: '#1E4CA1' },
        { name: 'Light Racing Blue Satin', colorCode: '#3A75C4' },
        { name: 'Naiade Green Satin', colorCode: '#2E8B57' },
        { name: 'Acid Green Satin', colorCode: '#B0BF1A' },
        { name: 'Santi Grey Metallic Satin', colorCode: '#7D7F85' },
        { name: 'Argentic Grey Satin', colorCode: '#A9A9A9' },
        { name: 'Canyon Copper Metallic Satin', colorCode: '#996633' },
        { name: 'Deep Black Satin', colorCode: '#0D0D0D' }
    ],
    Matte: [
        { name: 'Glacier White Matte', colorCode: '#EFF2F4' },
        { name: 'Florida Yellow Matte', colorCode: '#FFD300' },
        { name: 'Lemon Yellow Matte', colorCode: '#FFF44F' },
        { name: 'Mandarin Red Matte', colorCode: '#D64527' },
        { name: 'Blood Red Matte', colorCode: '#660000' },
        { name: 'Fuchsia Matte', colorCode: '#C154C1' },
        { name: 'Night Blue Met Matte', colorCode: '#1A2B4C' },
        { name: 'Turquoise Blue Matte', colorCode: '#30D5C8' },
        { name: 'Wasabi Green Matte', colorCode: '#A8C545' },
        { name: 'Military Green Matte', colorCode: '' },
        { name: 'Adventures Green Matte', colorCode: '#355E3B' },
        { name: 'Sherwood Green Matte', colorCode: '#2A4D2E' },
        { name: 'Frozen Grey Matte', colorCode: '#CED0CF' },
        { name: 'Meteorite Grey Matte', colorCode: '#555D61' },
        { name: 'Cinder Rose Metal Matte', colorCode: '#7D4A58' },
        { name: 'Anthracite Grey Metallic Matte', colorCode: '#323232' },
        { name: 'Marrakesh Brown Matte', colorCode: '#323232' },
        { name: 'Deep Black Matte', colorCode: '#000000' }
    ],
    Metallic: [
        { name: 'Metallic Yellow Gloss Ara Blue Metallic Satin', colorCode: '#1E4CA1' }
    ]
};
